"""Public API of the PRISMA analytics baseline."""

from .exceptions import AnalyticsError, AnalyticsValidationError
from .models import (
    AnalysisMode,
    CollectionItem,
    CollectionSchema,
    IterationStrategy,
    ObservationTrace,
    PairAggregation,
    PairResponse,
    ResponseStatus,
    SessionMetadata,
    StimulusType,
    TimeAlgorithm,
)
from .pair_compare import (
    ALGORITHM_VERSION,
    CONSISTENCY_THRESHOLD,
    FASTEST_MAJORITY_OBSERVATIONS,
    aggregate_pair_observations,
    analyze_session,
    build_collection_binary_matrix,
    build_pair_time_matrix,
    build_time_weighted_matrix,
    calculate_next_raw_weights,
    calculate_consistency,
    compare_analysis_modes,
    compute_validation_total_time,
    iterate_rank_weights,
)

__all__ = [
    "ALGORITHM_VERSION",
    "CONSISTENCY_THRESHOLD",
    "FASTEST_MAJORITY_OBSERVATIONS",
    "AnalysisMode",
    "AnalyticsError",
    "AnalyticsValidationError",
    "CollectionItem",
    "CollectionSchema",
    "IterationStrategy",
    "ObservationTrace",
    "PairAggregation",
    "PairResponse",
    "ResponseStatus",
    "SessionMetadata",
    "StimulusType",
    "TimeAlgorithm",
    "aggregate_pair_observations",
    "analyze_session",
    "build_collection_binary_matrix",
    "build_pair_time_matrix",
    "build_time_weighted_matrix",
    "calculate_next_raw_weights",
    "calculate_consistency",
    "compare_analysis_modes",
    "compute_validation_total_time",
    "iterate_rank_weights",
]
